# Generated by Django 5.0.6 on 2024-05-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=45, unique=True)),
                ('mdp', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('idDivision', models.AutoField(primary_key=True, serialize=False)),
                ('typeDivision', models.CharField(choices=[('Niveau', 'Niveau'), ('Specialite', 'Specialite'), ('Section', 'Section'), ('Groupe', 'Groupe')], max_length=10)),
                ('libele', models.CharField(max_length=45)),
                ('nbrEtudiant', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'divisions',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('idEnseignant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45, null=True)),
                ('prenom', models.CharField(max_length=45, null=True)),
                ('grade', models.CharField(choices=[('MCA', 'MCA'), ('MCB', 'MCB'), ('Pr', 'Pr'), ('MAA', 'MAA'), ('Vac', 'Vac'), ('Doc', 'Doc')], max_length=3, null=True)),
                ('mail', models.CharField(max_length=90, null=True)),
                ('mdp', models.CharField(max_length=45, null=True)),
                ('heureMax', models.TimeField(default='06:00:00')),
            ],
            options={
                'db_table': 'enseignants',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('idHoraire', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(choices=[('Dim', 'Dim'), ('Lun', 'Lun'), ('Mar', 'Mar'), ('Mer', 'Mer'), ('Jeu', 'Jeu')], max_length=3, null=True)),
                ('heureD', models.CharField(choices=[('08h00', '08h00'), ('09h40', '09h40'), ('11h20', '11h20'), ('13h00', '13h00'), ('14h40', '14h40'), ('16h20', '16h20')], max_length=5, null=True)),
                ('heureF', models.CharField(choices=[('09h30', '09h30'), ('11h10', '11h10'), ('12h50', '12h50'), ('14h30', '14h30'), ('16h10', '16h10'), ('17h50', '17h50')], max_length=5, null=True)),
            ],
            options={
                'db_table': 'horaires',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('idModule', models.AutoField(primary_key=True, serialize=False)),
                ('libélé', models.CharField(max_length=90, unique=True)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('idSalles', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=45, unique=True)),
                ('capacite', models.IntegerField()),
                ('tp', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'salles',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('idEtudiant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('mdp', models.CharField(max_length=45)),
                ('idDivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiant.division')),
            ],
            options={
                'db_table': 'etudiants',
            },
        ),
        migrations.CreateModel(
            name='IndispoEnseignant',
            fields=[
                ('idIndspo', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(choices=[('Dim', 'Dim'), ('Lun', 'Lun'), ('Mar', 'Mar'), ('Mer', 'Mer'), ('Jeu', 'Jeu')], max_length=3, null=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('idEnseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.enseignant')),
            ],
            options={
                'db_table': 'indispoenseignant',
            },
        ),
        migrations.CreateModel(
            name='EtudierModule',
            fields=[
                ('idEtudierModule', models.AutoField(primary_key=True, serialize=False)),
                ('typeEtude', models.CharField(choices=[('COURS', 'COURS'), ('TD', 'TD'), ('TP', 'TP')], max_length=5)),
                ('idDivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.division')),
                ('idModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.module')),
            ],
            options={
                'db_table': 'etudiermodules',
            },
        ),
        migrations.CreateModel(
            name='EnseignerModule',
            fields=[
                ('idEnseignerModule', models.AutoField(primary_key=True, serialize=False)),
                ('typeEnseignement', models.CharField(choices=[('COURS', 'COURS'), ('TD', 'TD'), ('TP', 'TP')], max_length=5)),
                ('idEnseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.enseignant')),
                ('idModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.module')),
            ],
            options={
                'db_table': 'enseignermodules',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('idProgramme', models.AutoField(primary_key=True, serialize=False)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.enseignant')),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.horaire')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiermodule')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.salle')),
            ],
            options={
                'db_table': 'programme',
            },
        ),
    ]
