# Generated by Django 5.0.6 on 2024-06-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='indispoenseignant',
            constraint=models.CheckConstraint(check=models.Q(('start__lt', models.F('end'))), name='start_lt_end'),
        ),
    ]
